config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/dashboard", to: 'pages#dashboard'
  resources :animals do
    resources :bookings, only: [ :new, :create, :edit, :update ]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :animals
  resources :bookings do
    member do
      get "validate_booking"
    end
  end
  resources :reviews, only: [:new, :create]
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  # SPECIE for "rent your pet", to do later
  SPECIE = %w(Cat Dog Chicken Fish )

  geocoded_by :adress
  after_validation :geocode, if: :will_save_change_to_adress?
  validates :name, presence: true
  validates :age, presence: true
  validates :price, presence: true
  validates :specie, presence: true
  validates :adress, presence: true
  validates :photo, presence: true
  # validates :description, length: { minimum: 20,
  # too_short: "%{count} characters is the minimum allowed"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :animal
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :animals
  has_many :bookings
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @animals = policy_scope(Animal)
    @address_geocoded = ""
    # the `geocoded` scope filters only animals with coordinates (latitude & longitude)
    if params[:adress].empty?
      @animals = Animal.near([params[:latitude].to_f, params[:longitude].to_f], 50)
      @address_geocoded = Geocoder.search([params[:latitude].to_f, params[:longitude].to_f]).first.data["display_name"]
      @animals = @animals.where(specie: params[:specie])
    else
      @animals = @animals.near(params[:adress], 50)
      @animals = @animals.where(specie: params[:specie])
    end
    @markers = @animals.geocoded.map do |animal|
      { lat: animal.latitude, lng: animal.longitude, info_window: render_to_string(partial: "info_window", locals: { animal: animal })}
    end
  end

  def show
    @animal = Animal.find(params[:id])
    authorize @animal
  end

  def new
    @animal = Animal.new
    authorize @animal
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user
    authorize @animal
    if @animal.save
      redirect_to animals_path(@user)
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    authorize @animal
  end

  def update
    @animal = Animal.find(params[:id])
    @animal.update(animal_params)
    redirect_to animal_path(@animal)
    authorize @animal
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
    authorize @animal
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def animal_params
    params.require(:animal).permit(:name, :breed, :age, :price, :description, :specie, :adress, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @animal = Animal.find(params[:animal_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @animal = Animal.find(params[:animal_id])
    @booking.animal = @animal
    @booking.status = false
    authorize @booking
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def validate_booking
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(status: true)
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @inprogress_bookings = Booking.where(user: current_user, status: false)
    @validated_bookings = Booking.where(user: current_user, status: true)
    @animals = current_user.animals
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include Pundit
  def new
    @review = Review.new
    authorize @review

  end

  def create
    @review = Review.new(review_params)
    authorize @review
    @review.user = user
    if @review.save
      redirect_to new_review_path
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_info_window.html.erb
<h2><%= animal.name %></h2>
<p><%= animal.adress %></p>

app/views/animals/edit.html.erb
<h3>Edit a animal</h3>
  <%= simple_form_for @animal do |f| %>
    <%= f.input :name, placeholder: 'Enter a name' %>
    <%= f.input :breed, placeholder: 'Enter a breed' %>
    <%= f.input :age, placeholder: 'Enter an age' %>
    <%= f.input :price, placeholder: 'Enter a price' %>
    <%= f.input :description, placeholder: 'Enter a description' %>
    <%= f.input :specie, collection: Animal::SPECIE %>
    <%= f.input :adress, placeholder: 'Enter an address' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-flat' %>
    <%= link_to "Back", animals_path %>
  <% end %>

app/views/animals/index.html.erb
<div class="content" id="contain-map-and-animals" >
  <div style="width: 40%; height: 80vh; position: sticky !important; top:90px">
    <%= form_tag animals_path, method: :get, class: "form-inline md-form mr-auto mb-4" do %>
      <%= text_field_tag :adress,
        params[:adress],
        class: "form-control mr-sm-2",
        placeholder: "Address",
        value: @address_geocoded
      %>
      <%= hidden_field_tag "latitude" %>
      <%= hidden_field_tag "longitude" %>
      <%= select_tag 'specie', options_for_select(Animal::SPECIE), class: "form-control mr-sm-2" %>
      <%= submit_tag "Search", class: "btn-flat btn-flat:hover border-0 font-weight-bold" %>
    <% end %>
    <div class="map" id="map"

      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      data-markers="<%= @markers.to_json %>">
    </div>
  </div>

  <div class="cards">
    <% @animals.each do |animal| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(animal.photo.key) %>)">
        <%= link_to animal.name, animal_path(animal) %>
      </div>
    <% end %>
  </div>
</div>

app/views/animals/new.html.erb
<div id="rent-animal" class="container mx-auto mt-5" style="width: 500px;">
  <h3>Add a animal</h3>
    <%= simple_form_for @animal do |f| %>
      <%= f.input :name, placeholder: 'Enter a name' %>
      <%= f.input :breed, placeholder: 'Enter a breed' %>
      <%= f.input :age, placeholder: 'Enter an age' %>
      <%= f.input :price, placeholder: 'Enter a price' %>
      <%= f.input :description, placeholder: 'Enter a description' %>
      <%= f.input :specie, collection: Animal::SPECIE %>
      <%= f.input :adress, placeholder: 'Enter an address', input_html: {id: "animal_address"}%>
      <%= f.input :photo, as: :file %>
      <%= f.submit class: 'btn btn-flat' %>
      <%= link_to "Back", animals_path %>
    <% end %>
</div>

app/views/animals/show.html.erb
<div id="body-show">
  <div id="c-show" class="container">
    <%= cl_image_tag @animal.photo.key, class:"img-show" %>
    <div class="description-container">
            <h3 class="card-title"><strong><%= @animal.name %></strong></h3>
            <p class="card-text">breed : <strong><%= @animal.breed %></strong></p>
            <p class="card-text">Address : <strong><%= @animal.adress %></strong></p>
            <p class="card-text">Age : <strong><%= @animal.age %></strong> year(s)</p>
            <p class="card-text">Price : <strong><%= @animal.price %></strong> euros</p>
            <p class="card-text">Description : <strong><%= @animal.description %></strong></p>
            <p class="card-text">specie : <strong><%= @animal.specie %></strong></p>
            <% unless @animal.user == current_user %>
              <%= link_to "Rent", new_animal_booking_path(@animal), class: 'btn btn-flat'%>
            <% end %>
    </div>
    <div class="back-btn">
      <%= link_to "Back", root_path %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container d-flex">
  <div class="details">
  <h2>Date of location</h2>
    <div class="container-form">
      <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
        <%= simple_form_for :search, method: "get" do |f| %>
        <%= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker"} %>
        <% end %>
      </div>
    </div>
  <h2>Paiement :</h2>
  <div class="btn-pay">
  <button type="button" class="btn-new btn btn-outline-success">CB</button>
  <button type="button" class="btn-new btn btn-outline-success">Paypal</button>
  </div>

  </div>
    <div class="card-details">
      <div class="img-booking">
        <%= cl_image_tag @animal.photo.key, class:"img-show" %>
      </div>
        <p class="name"><%= @animal.name %></p>
        <p class="infos"><u><strong>Description :</strong></u> <%= @animal.description %></p>
        <p class="infos"><u><strong>Address :</strong></u> <%= @animal.adress %></p>
        <p class="infos"><u><strong>Specie :</strong></u> <%= @animal.specie %></p>

        <div class="price">
          <h2>Price : <span id="animal-price"><%= @animal.price %></span> $</h2>
          <h2>Day(s) : <span id="total-days">1</span></h2>
          <h2>Total : <span id="total-price"><%= @animal.price %></span> $</h2>
          <div class="btn-booking">
          <button type="button" id ="btn-payment" class="btn btn-flat not-active" data-toggle="modal" data-target="#exampleModalCenter">
            Confirm paiement
          </button>
          </div>
        </div>



    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLongTitle">Do you confirm your book ? 🐒</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3><p class="card-text">From: <strong><span id="start-date-booking"></span></strong> To: <strong><span id="end-date-booking"></span></strong></p></h3>
      </div>
      <div class="modal-footer">
        <%= link_to "Cancel", animal_path(@animal), class: "btn btn-flat", id: "btn-red" %>
        <%= simple_form_for([@animal, Booking.new]) do |f| %>
          <%= f.input :start_date, as: :hidden, html5: true %>
          <%= f.input :end_date, as: :hidden, html5: true %>
          <%= f.submit class: "btn btn-flat"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tamagotchi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <p class="alert"><%= alert %></p>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="content">
  <h1>Hello, <%= "#{@user.first_name} #{@user.last_name}" %></h1>
</div>
<div class="container mt-2">
  <ul class="nav nav-tabs">
      <li class="nav-item">
          <a class="nav-link active" data-bs-toggle="tab" href="#home">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
            </svg>Booking in progress</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" data-bs-toggle="tab" href="#profile">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-bounding-box" viewBox="0 0 16 16">
            </svg>Booking validated</a>
      </li>
      <li class="nav-item">
          <a class="nav-link3" data-bs-toggle="tab" href="#contact">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
            </svg>My animals</a>
      </li>
  </ul>
  <div class="tab-content">
      <div class="tab-pane active" id="home">
          <div class="row border g-0 rounded">
              <div class="col p-4">
                <% @inprogress_bookings.each do |booking|%>
                  <div class="tout d-flex justify-content-around align-items-center">
                    <div class="box-animal">
                     <strong><h1>Animal : </h1></strong>
                      <h3 class="card-title"><strong><%= booking.animal.name %></strong></h3>
                        <p class="card-text">breed : <strong><%= booking.animal.breed %></strong></p>
                        <p class="card-text">Address : <strong><%= booking.animal.adress %></strong></p>
                        <p class="card-text">Date : <strong><%= "#{booking.start_date.strftime("%A, %b %d")} / #{booking.end_date.strftime("%A, %b %d")}"%></strong></p>
                        <p class="card-text">Description : <strong><%= booking.animal.description %></strong></p>
                        <p class="card-text">specie : <strong><%= booking.animal.specie %></strong></p>
                    </div>
                    <div class="box-user">
                       <strong><h1>User : </h1></strong>
                      <div class="d-flex py-3">
                      <h3 class="card-title"><strong><%= booking.animal.user.first_name %></strong></h3>
                      <h3 class="card-title"><strong><%= booking.animal.user.last_name %></strong></h3>   
                      </div>
                    </div>
                    <%= link_to "valider le booking", validate_booking_booking_path(booking), class: "btn-flat", id:"for-validate"%>
                  </div>
                <% end %>
              </div>
          </div>
      </div>
      <div class="tab-pane" id="profile">
          <div class="row border g-0 rounded">
              <div class="col p-4">
                  <% @validated_bookings.each do |booking|%>
                  <div class="tout d-flex justify-content-around align-items-center">
                    <div class="box-animal">
                     <strong><h1>Animal : </h1></strong>
                      <h3 class="card-title"><strong><%= booking.animal.name %></strong></h3>
                        <p class="card-text">breed : <strong><%= booking.animal.breed %></strong></p>
                        <p class="card-text">Address : <strong><%= booking.animal.adress %></strong></p>
                        <p class="card-text">Date : <strong><%= "#{booking.start_date.strftime("%A, %b %d")} / #{booking.end_date.strftime("%A, %b %d")}"%></strong></p>
                        <p class="card-text">Description : <strong><%= booking.animal.description %></strong></p>
                        <p class="card-text">specie : <strong><%= booking.animal.specie %></strong></p>
                    </div>
                    <div class="box-user">
                       <strong><h1>User : </h1></strong>
                      <div class="d-flex py-3">
                      <h3 class="card-title"><strong><%= booking.animal.user.first_name %></strong></h3>
                      <h3 class="card-title"><strong><%= booking.animal.user.last_name %></strong></h3>   
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
          </div>
      </div>
      <div class="tab-pane" id="contact">
          <div class="row border g-0 rounded">
              <div class="col p-4">
                  <% @animals.each do |animal|%>
                    <div id="c-show-dashboard" class="container">
                      <%= cl_image_tag animal.photo.key, class:"img-show-dashboard" %>
                      <div class="description-container">
                        <h3 class="card-title"><strong><%= animal.name %></strong></h3>
                        <p class="card-text">breed : <strong><%= animal.breed %></strong></p>
                        <p class="card-text">Address : <strong><%= animal.adress %></strong></p>
                        <p class="card-text">Age : <strong><%= animal.age %></strong> year(s)</p>
                        <p class="card-text">Price : <strong><%= animal.price %></strong> euros</p>
                        <p class="card-text">Description : <strong><%= animal.description %></strong></p>
                        <p class="card-text">specie : <strong><%= animal.specie %></strong></p>
                          <%= link_to "Edit", edit_animal_path(animal), class: 'btn btn-flat'%>
                          <%= link_to "Delete", animal_path(animal), class: 'btn btn-flat', method: :delete, data: { confirm: "Are you sure?" } %>
                      </div>
                    </div>
                  <% end %>
              </div>
          </div>
      </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1602847213180-50e43a80bef4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <div class="search-home">
    <h1>Have a break, Rent a pet 🦄 </h1>
      <%= form_tag animals_path, method: :get, class: "form-inline md-form mr-auto mb-4" do %>
        <%= text_field_tag :adress,
          params[:adress],
          class: "form-control mr-sm-2",
          placeholder: "Address"
        %>
        <%= hidden_field_tag "latitude" %>
        <%= hidden_field_tag "longitude" %>

        <%= select_tag 'specie', options_for_select(Animal::SPECIE), class: "form-control mr-sm-2" %>
        <%= submit_tag "Search", class: "btn-flat btn-flat:hover border-0 font-weight-bold" %>
      <% end %>
    </div>
  </div>
</div>

<div class="step">
  <div class="card-step">
  <img src="http://parallelstudio.tv/wp-content/uploads/2018/11/new-york-times-illustration-christmas3.jpg" alt="" id="step-1-img">
  <h3>Step 1</h3>
  <p>Enter your city and a category </p>
  </div>
  <div class="card-step">
  <img src="https://i.pinimg.com/736x/1c/b1/4f/1cb14fc70af8b59f01b8b258443ca98f.jpg" alt="" id="step-1-img">
  <h3>Step 2</h3>
  <p>Choose your pet</p>
  </div>
  <div class="card-step">
  <img src="https://www.studyrama.com/IMG/arton95383.png" alt="" id="step-1-img">
  <h3>Step 3</h3>
  <p>Confirm your pet</p>
  </div>
  <div class="card-step">
  <img src="http://www.stenaline.ie/-/media/Images/irish-seas/routes/pets/belfast-cairnryan-pets-og.jpg" alt="" id="step-1-img">
  <h3>Step 4</h3>
  <p>Have fun with your pet</p>
  </div>
</div>

<div class="card-category" style="background-image: linear-gradient(to left, black 27%,transparent 73%), url(https://images.unsplash.com/photo-1490042706304-06c664f6fd9a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80)">
  <div class="text-card-category">
    <div>
      <h2>Rent your pet</h2>
      <p>Take time for yourself and earn money</p>
    </div>

    <%= link_to "Rent", new_animal_path, class: "btn btn-flat" %>
  </div>
</div>

<%= render 'shared/review-page' %>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for @review do |f| %>
        <%= f.input :comment %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
        <%= f.submit "Send your review" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  <%= image_tag "logo.png", id: 'logo-footer' %>
     Tamagotchi pour les grands et les petits ♥️
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h2><%= image_tag "logo.png" %> Tamagotchi</h2>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Rent your pet", new_animal_path, class: "nav-link" %>
        </li>
        <li><%= link_to "Hi #{current_user.first_name} ✌🏾", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar-will.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Rent your pet", new_user_session_path, class: "nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_review-page.html.erb
<div class="container-review">
  <div class="container-notification">
    <div class="notification">
      <img src='https://avatars.githubusercontent.com/u/57566457?v=4' class="avatar-large"/>
      <div class="notification-content">
        <p><small>20th August </small></p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
        <p>This site is really great, well done to the founders of this site</p>
      </div>
    </div>

    <div class="notification">
      <img src='https://avatars.githubusercontent.com/u/25443871?v=4' class="avatar-large"/>
      <div class="notification-content">
        <p><small>16th August </small></p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
        <p>What an incredible experience thanks to this site</p>
      </div>
    </div>

    <div class="notification">
      <img src='https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1544604383/pnqv3gmdpbtqrstpqgls.jpg' class="avatar-large"/>
      <div class="notification-content">
        <p><small>15th August </small></p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
        <p>I love this website</p>
      </div>
    </div>

      <div class="notification">
      <img src='https://ca.slack-edge.com/T02NE0241-U02NE1NL9-40998e0a5c92-72' class="avatar-large" />
      <div class="notification-content">
        <p><small>14th August </small></p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
        <p>An excellent user experience</p>
      </div>
    </div>
  </div>

  <div class="container-notification">
    <div class="notification">
      <img src='https://avatars.githubusercontent.com/u/62572114?v=4' class="avatar-large"/>
      <div class="notification-content">
        <p><small>12th August </small></p> <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
        <p>One-click reservation, fast and efficient</p>
      </div>
    </div>

    <div class="notification">
      <img src='https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1609346642/odae0n6o1q5dv1fiqzj4.jpg' class="avatar-large"/>
      <div class="notification-content">
        <p><small>9th August </small></p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
        <p>I spent the best day of my life renting a fish, thank you</p>
      </div>
    </div>

    <div class="notification">
      <img src='https://avatars.githubusercontent.com/u/54894352?v=4' class="avatar-large"/>
      <div class="notification-content">
        <p><small>7th August </small></p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
        <p>Simple and easy to book</p>
      </div>
    </div>

    <div class="notification">
      <img src='https://avatars.githubusercontent.com/u/8093761?v=4' class="avatar-large"/>
      <div class="notification-content">
        <p><small>5th August </small></p> <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
        <p>I earned more than 1000 $ in a month thanks to this website</p>
      </div>
    </div>
  </div>
</div>